name: list_mingle
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0-210.3.beta <4.0.0"
  flutter: ">=3.13.8"

dependencies:
  firebase_core: ^2.20.0
  firebase_database: ^10.3.2
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_hooks: ^0.20.3
  hooks_riverpod: ^2.4.4
  riverpod: ^2.4.4
  shared_preferences: ^2.2.2
  uuid: ^4.1.0

dev_dependencies:
  custom_lint: ^0.5.4
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  riverpod_lint: ^2.3.2

flutter:
  uses-material-design: true
  fonts:
    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
